setting up compile to copy view packages to stage

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -16,13 +16,26 @@ if [ ! -f "${ENV_DIR}/APP_BASE" ]; then
     echo "APP_BASE was not set. Aborting" | indent
     exit 1
 fi
+
+if [ ! -f "${ENV_DIR}/LANDING_VIEW_BASE" ]; then
+    echo "LANDING_VIEW_BASE was not set. Aborting" | indent
+    exit 1
+fi
+
+if [ ! -f "${ENV_DIR}/REACT_VIEW_BASE" ]; then
+    echo "REACT_VIEW_BASE was not set. Aborting" | indent
+    exit 1
+fi
+
 APP_BASE="$(cat "${ENV_DIR}/APP_BASE")"
-LANDING_BASE="$(cat "${ENV_DIR}/LANDING_BASE")"
+LANDING_VIEW_BASE="$(cat "${ENV_DIR}/LANDING_VIEW_BASE")"
+REACT_VIEW_BASE="$(cat "${ENV_DIR}/REACT_VIEW_BASE")"
 
 (
-    mkdir "${STAGE}/view" &&
+    mkdir -p "${STAGE}/packages/$(basename "$LANDING_VIEW_BASE")" "${STAGE}/packages/$(basename "$REACT_VIEW_BASE")" &&
     mv "${BUILD_DIR}/${APP_BASE}" "${STAGE}" &&
-    mv "${BUILD_DIR}/${LANDING_BASE}" "${STAGE}/view" &&
+    mv "${BUILD_DIR}/${LANDING_VIEW_BASE}" "${STAGE}" &&
+    mv "${BUILD_DIR}/${REACT_VIEW_BASE}" "${STAGE}" &&
     rm -rf "${BUILD_DIR}"/* &&
     mv "${STAGE}/$(basename "$APP_BASE")"/* "${BUILD_DIR}"
 )
